[package]
name = "cb-plugin-api"
version = "1.0.0-beta"
edition = "2021"

[dependencies]
cb-types = { path = "../cb-types" }
cb-core = { path = "../cb-core" }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }